# Generated by Django 3.2 on 2022-05-24 20:20

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cms', '0022_auto_20180620_1551'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', help_text='Your name', max_length=64, verbose_name='Name')),
                ('company', models.CharField(blank=True, default='', help_text='Your organization’s name', max_length=64, verbose_name='Company or Organization')),
                ('email', models.EmailField(blank=True, default='', error_messages={'invalid': 'Please enter a correctly formatted email address.'}, help_text='Your email address', max_length=255, verbose_name='Email')),
                ('telephone', models.CharField(blank=True, default='', help_text='If you wish to be contacted by phone, please ensure you enter the correct number here.', max_length=32, verbose_name='Telephone Number')),
                ('comments', models.TextField(blank=True, default='', help_text='Please let us know what is on your mind.', verbose_name='Comment or Question')),
                ('contact_date', models.DateTimeField(blank=True, default=django.utils.timezone.now, help_text='When this person completed the contact form.', verbose_name='contact date')),
                ('was_contacted', models.BooleanField(default=False, help_text='Check this if someone has already reached out to this person.', verbose_name='has been contacted?')),
                ('notes', models.TextField(blank=True, default='', help_text='Internal notes relating to contacting this person.', verbose_name='contact notes')),
                ('referer', models.CharField(blank=True, default='', help_text='This is the page the visitor was on before coming to the contact page.', max_length=2048, verbose_name='referring page')),
            ],
        ),
        migrations.CreateModel(
            name='ContactPluginModel',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='contacts_contactpluginmodel', serialize=False, to='cms.cmsplugin')),
                ('title', models.CharField(blank=True, help_text='Optional. Title of the widget.', max_length=64, verbose_name='title')),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
    ]
