# Generated by Django 3.2 on 2022-07-12 01:33

import cms.models.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cms', '0022_auto_20180620_1551'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductsCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', help_text='Please provide a unique name for this product category.', max_length=64, unique=True, verbose_name='category name')),
                ('slug', models.SlugField(default='', help_text='Please ensure there is a unique “slug” for this product category.', max_length=255, unique=True, verbose_name='slug')),
                ('avatar', models.ImageField(default='', help_text='Please provide a unique name for this product category.', upload_to='', verbose_name='avatar image')),
                ('descn', models.CharField(default='', help_text='Please ensure there is a unique “slug” for this product category.', max_length=500, verbose_name='description')),
            ],
            options={
                'verbose_name_plural': 'product categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ProductsItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline', models.CharField(default='', help_text='Please provide a unique headline for this produc item.', max_length=255, verbose_name='headline')),
                ('slug', models.SlugField(default='', help_text='Please ensure there is a unique “slug” for this produc item. Note, it is strongly recommended that this does not change after publishing this produc item.', max_length=255, verbose_name='slug')),
                ('announcement', models.BooleanField(default=False, help_text='Check this box to display this item in the Announcements box on the front page.', verbose_name='announcement?')),
                ('announcement_title', models.CharField(blank=True, default='', help_text='Optional. Alternate title to be used in the Announcements Box on the front page.', max_length=255, verbose_name='announcement title')),
                ('subtitle', models.CharField(blank=True, default='', help_text='Optional. Please provide a unique subtitle for this produc item.', max_length=255, verbose_name='subtitle')),
                ('published', models.BooleanField(default=False, help_text='Check to allow this produc post to be publically visible', verbose_name='pubished')),
                ('product_date', models.DateTimeField(default=django.utils.timezone.now, help_text='Please provide the date of this produc item. Note, setting this to a future date will prevent this produc item from appearing until that time.', verbose_name='product date')),
                ('mod_date', models.DateTimeField(auto_now=True, verbose_name='modification date')),
                ('key_image', models.ImageField(default='', help_text='Optional. Please supply an image, if one is desired. This will be resized automatically.', upload_to='', verbose_name='category name')),
                ('key_image_tooltip', models.CharField(blank=True, default='', help_text='Optional. Provide a short description of the key image (if present) for its “tooltip”', max_length=255, verbose_name='key image tooltip')),
                ('categories', models.ManyToManyField(help_text='Please select one or more categories for this produc item.', related_name='product_items', to='products.ProductsCategory')),
                ('product_body', cms.models.fields.PlaceholderField(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, slotname='product_item_body', to='cms.placeholder')),
            ],
            options={
                'ordering': ['-product_date'],
            },
        ),
    ]
